version: "3.8"
services:
  nebulasync:
    image: python:3.10-slim
    command: >
      sh -c "pip install requests && python -u /app/pisync.py"
    volumes:
      - ./pisync.py:/app/pisync.py
    networks:
      - proxy
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.hostname != docker-manager-03
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: any

networks:
  proxy:
    external: true