services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    networks:
      - proxy
      - termix-net
    volumes:
      - /mnt/cephfs/docker-cluster/Docker-Swarm/termix/data:/app/data
    environment:
      - PORT=8080
      - TZ=Europe/Paris
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=proxy"
        - "traefik.http.routers.termix.rule=Host(`termix.test.teamfnb.com`)"
        - "traefik.http.routers.termix.entrypoints=websecure"
        - "traefik.http.routers.termix.tls.certresolver=cloudflare"
        - "traefik.http.routers.termix.middlewares=default-headers@file"
        - "traefik.http.services.termix.loadbalancer.server.port=8080"

  guacd:
    image: guacamole/guacd:1.6.0
    networks:
      - termix-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

networks:
  proxy:
    external: true
  termix-net:
    driver: overlay
    attachable: true