services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - proxy
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  pve-exporter:
    # IMAGE CORRIGÉE ICI
    image: prompve/prometheus-pve-exporter:latest
    networks:
      - proxy
    # L'exportateur écoute par défaut sur le port 9221
    ports:
      - "9221:9221"
    volumes:
      - ./pve.yml:/etc/prometheus/pve.yml:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  grafana:
    image: grafana/grafana-oss:latest
    networks:
      - proxy
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # À changer à la première connexion
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_ROOT_URL=https://grafana.test.teamfnb.com
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
          - "traefik.enable=true"
          - "traefik.swarm.network=proxy"
          - "traefik.http.routers.grafana-router.rule=Host(`grafana.test.teamfnb.com`)"
          - "traefik.http.routers.grafana-router.entrypoints=websecure"
          - "traefik.http.routers.grafana-router.tls.certresolver=cloudflare"
          - "traefik.http.routers.grafana-router.middlewares=default-headers@file" # AJOUTÉ
          - "traefik.http.services.grafana-svc.loadbalancer.server.port=3000"
networks:
  proxy:
    external: true