services:
  dozzle:
    image: amir20/dozzle:latest
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Paris
      - DOZZLE_MODE=swarm
      - DOZZLE_FILTER=status=running
    deploy:
      mode: global  # Une instance sur chaque manager (Tom, Zakh, Ilan)
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=proxy"
        - "traefik.http.routers.dozzle.rule=Host(`logs.test.teamfnb.com`)"
        - "traefik.http.routers.dozzle.entrypoints=websecure"
        - "traefik.http.routers.dozzle.tls=true"
        - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
        - "traefik.http.routers.NOM_DU_SERVICE.middlewares=secHeaders@file"

networks:
  proxy:
    external: true