services:
  pihole:
    image: pihole/pihole:latest
    hostname: "{{.Node.Hostname}}"
    networks:
      - proxy
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - TZ=Europe/Paris
      - FTLCONF_webserver_port=8080
      - FTLCONF_webserver_api_password=password
      - FTLCONF_webserver_domain=pihole.test.teamfnb.com
      - FTLCONF_webserver_trustedProxies=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - FTLCONF_dns_listeningMode=all
      - FTLCONF_dns_hostRecord=pihole.test.teamfnb.com,192.168.50.36
    volumes:
      - /mnt/cephfs/docker-cluster/Docker-Swarm/pihole/{{.Node.Hostname}}/config:/etc/pihole
      - /mnt/cephfs/docker-cluster/Docker-Swarm/pihole/{{.Node.Hostname}}/dnsmasq.d:/etc/dnsmasq.d
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          #- node.hostname == docker-manager-01
      update_config:
        order: stop-first
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=proxy"
        - "traefik.http.routers.pihole.rule=Host(`pihole.test.teamfnb.com`)"
        - "traefik.http.routers.pihole.priority=10" # <--- Priorité basse (Backup)
        - "traefik.http.routers.pihole.entrypoints=websecure"
        - "traefik.http.routers.pihole.tls=true"
        - "traefik.http.routers.pihole.tls.certresolver=cloudflare"
        - "traefik.http.services.pihole.loadbalancer.server.port=8080"
        - "traefik.http.routers.pihole.middlewares=pihole-proto"
        - "traefik.http.middlewares.pihole-proto.headers.customrequestheaders.X-Forwarded-Proto=https"

networks:
  proxy:
    external: true