services:
  traefik:
    image: traefik:v3.6.5
    container_name: traefik
    restart: always
    command:
      # --- Configuration Statique ---
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--api.dashboard=true"
      # --- Provider Swarm (Syntaxe v3) ---
      - "--providers.swarm=true"
      - "--providers.swarm.network=proxy"
      - "--providers.swarm.exposedByDefault=false"
      # --- Provider File (Approche Lempa) ---
      - "--providers.file.directory=/etc/traefik/rules"
      - "--providers.file.watch=true"
      # --- Entrypoints ---
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # --- Certificats Cloudflare ---
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=fnb2@orange.fr"
      - "--certificatesresolvers.cloudflare.acme.storage=/etc/traefik/acme.json"
    networks:
      - proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/mnt/cephfs/docker-cluster/Docker-Swarm/traefik/data/acme.json:/etc/traefik/acme.json"
      - "/mnt/cephfs/docker-cluster/Docker-Swarm/traefik/rules:/etc/traefik/rules:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - CF_API_EMAIL=fnb2@orange.fr
      - CF_API_KEY=59caaee466390f1db7c67c90db68d14fc515f
      - TZ=Europe/Paris
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # Dashboard Traefik mis à jour
        - "traefik.http.routers.traefik-dash.rule=Host(`traefik-dashboard1.test.teamfnb.com`)"
        - "traefik.http.routers.traefik-dash.service=api@internal"
        - "traefik.http.routers.traefik-dash.entrypoints=websecure"
        - "traefik.http.routers.traefik-dash.tls.certresolver=cloudflare"
        - "traefik.http.services.traefik-dash.loadbalancer.server.port=8080"
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"

networks:
  proxy:
    external: true