version: '3.9'

services:
  traefik:
    image: traefik:v3.6.5
    command:
      - "--log.level=DEBUG"
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--providers.swarm=true"
      - "--providers.swarm.network=proxy"
      - "--providers.swarm.exposedByDefault=false"
      - "--providers.file.directory=/etc/traefik/rules"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      
      # --- RESOLVER CLOUDFLARE UNIQUE ---
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=fnb2@orange.fr"
      - "--certificatesresolvers.cloudflare.acme.storage=/etc/traefik/acme.json"
      - "--certificatesresolvers.cloudflare.acme.preferredchain=ISRG Root X1"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.propagation.delaybeforechecks=60"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.disablepropagationcheck=true"
      
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"

    networks:
      - proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/mnt/cephfs/docker-cluster/Docker-Swarm/traefik/data/acme.json:/etc/traefik/acme.json"
      - "/mnt/cephfs/docker-cluster/Docker-Swarm/traefik/rules:/etc/traefik/rules:ro,slave"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - CF_API_EMAIL=fnb2@orange.fr
      - CF_API_KEY=59caaee466390f1db7c67c90db68d14fc515f
      - TZ=Europe/Paris
      - LEGO_EXPERIMENTAL_CNAME_SUPPORT=true
      - TECHNITIUM_API_URL=http://192.168.50.104:5380
      - TECHNITIUM_API_TOKEN=a72b60e57e9746782820d0077b8b8f1df329e723d160cb2c3f296487d647300c
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=false"
        - "traefik.swarm.network=proxy"
        
        # --- Certificats Wildcard via Cloudflare ---
        - "traefik.http.routers.wildcard-certs.tls.certresolver=cloudflare"
        - "traefik.http.routers.wildcard-certs.tls.domains[0].main=test.teamfnb.com"
        - "traefik.http.routers.wildcard-certs.tls.domains[0].sans=*.test.teamfnb.com"
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"

networks:
  proxy:
    external: true