http:
  routers:
    # Router pour TrueNAS
    truenas:
      rule: "Host(`truenas.test.teamfnb.com`)"
      service: truenas-service
      entryPoints: [websecure]
      tls: { certResolver: cloudflare }

  services:
    truenas-service:
      loadBalancer:
        serversTransport: pve-transport # On réutilise ce transport pour ignorer le SSL interne
        servers:
          - url: "https://192.168.50.55" # Vérifie si ton TrueNAS est bien en HTTPS (.55)