http:
  routers:
    chatai:
      entryPoints: ["websecure"]
      rule: "Host(`chat.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "chatai"
    stable-diffusion:
      entryPoints: ["websecure"]
      rule: "Host(`stable-diffusion.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "stable-diffusion"
    ollama:
      entryPoints: ["websecure"]
      rule: "Host(`ollama.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "ollama"
    whisper:
      entryPoints: ["websecure"]
      rule: "Host(`whisper.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "whisper"

  services:
    chatai:
      loadBalancer:
        servers: [{ url: "http://192.168.50.8:8090" }]
    stable-diffusion:
      loadBalancer:
        servers: [{ url: "http://192.168.50.8:7860" }]
    ollama:
      loadBalancer:
        servers: [{ url: "http://192.168.50.8:11434" }]
    whisper:
      loadBalancer:
        servers: [{ url: "http://192.168.50.8:99" }]