http:
  routers:
    prowlarr:
      entryPoints: ["websecure"]
      rule: "Host(`prowlarr.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "prowlarr"
    radarr:
      entryPoints: ["websecure"]
      rule: "Host(`radarr.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "radarr"
    sonarr:
      entryPoints: ["websecure"]
      rule: "Host(`sonarr.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "sonarr"
    readarr:
      entryPoints: ["websecure"]
      rule: "Host(`readarr.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "readarr"
    bazarr:
      entryPoints: ["websecure"]
      rule: "Host(`bazarr.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "bazarr"

  services:
    prowlarr:
      loadBalancer:
        servers: [{ url: "http://192.168.50.55:9696" }]
    radarr:
      loadBalancer:
        servers: [{ url: "http://192.168.50.55:7878" }]
    sonarr:
      loadBalancer:
        servers: [{ url: "http://192.168.50.55:8989" }]
    readarr:
      loadBalancer:
        servers: [{ url: "http://192.168.50.55:8787" }]
    bazarr:
      loadBalancer:
        servers: [{ url: "http://192.168.50.55:6767" }]