http:
  routers:
    pihole-master:
      rule: "Host(`pihole.test.teamfnb.com`)"
      # On met une priorité énorme pour être SÛR qu'elle écrase le 10 et le 100
      priority: 5000 
      entryPoints:
        - websecure
      # On utilise le nom exact du service qui est VERT sur ton image 1
      service: pihole@swarm 
      middlewares:
        - default-headers
      tls:
        certResolver: cloudflare

  # On peut laisser les définitions de services ici, mais le routeur va les ignorer pour ce test
  services:
    pihole-swarm-internal:
      loadBalancer:
        servers:
          - url: "http://pihole_pihole:8080"

  middlewares:
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://*.ui.com https://*.ubnt.com; font-src 'self' data:; connect-src 'self' https://*.ui.com; frame-ancestors 'none';"
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https