http:
  # --- NOUVELLE SECTION : Pour ignorer les erreurs de certificat interne ---
  serversTransports:
    technitium-transport:
      insecureSkipVerify: true

  routers:
    # --- ROUTER : TRAEFIK DASHBOARD ---
    traefik-dash:
      rule: "Host(`traefik-dashboard.test.teamfnb.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`) || PathPrefix(`/`))"
      priority: 1000
      entryPoints:
        - websecure
      service: api@internal
      middlewares:
        - dashboard-redirect
        - default-headers
      tls:
        certResolver: cloudflare

    # --- ROUTER : TECHNITIUM CLUSTER UI ---
    # AJOUT DES NOMS dns-tom ET dns-zakh ICI
    technitium-admin:
      rule: "Host(`technitium.test.teamfnb.com`) || Host(`dns-tom.test.teamfnb.com`) || Host(`dns-zakh.test.teamfnb.com`)"
      priority: 1000
      entryPoints:
        - websecure
      service: technitium-cluster
      middlewares:
        - default-headers
      tls:
        certResolver: cloudflare

  middlewares:
    dashboard-redirect:
      redirectRegex:
        permanent: true
        regex: "^https://traefik-dashboard.test.teamfnb.com/?$"
        replacement: "https://traefik-dashboard.test.teamfnb.com/dashboard/"

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://*.ui.com https://*.ubnt.com; font-src 'self' data:; connect-src 'self' https://*.ui.com; frame-ancestors 'self';"
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: "https"

  services:
    # --- SERVICE : LOAD BALANCER TECHNITIUM ---
    technitium-cluster:
      loadBalancer:
        serversTransport: technitium-transport
        sticky:
          cookie:
            name: technitium_session
            httpOnly: true
            secure: true
        servers:
          - url: "https://192.168.50.104:53443" # Pi4
          - url: "https://192.168.50.61:53443"  # Tom
          - url: "https://192.168.50.62:53443"  # Zakh