http:
  routers:
    # --- Home Assistant ---
    homeassistant:
      entryPoints: ["websecure"]
      rule: "Host(`homeassistant.test.teamfnb.com`)"
      middlewares: ["middlewares-authentik"]
      priority: 10
      tls: { certResolver: "cloudflare" }
      service: "homeassistant"

    # --- Pi-hole ---
    pihole:
      entryPoints: ["websecure"]
      rule: "Host(`pihole.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "pihole"

    # --- Homebridge (Standard) ---
    homebridge:
      entryPoints: ["websecure"]
      rule: "Host(`homebridge.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "homebridge"

    # --- Homebridge-Pi ---
    homebridge-pi:
      entryPoints: ["websecure"]
      rule: "Host(`homebridge-pi.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "homebridge-pi"

    # --- Plex ---
    plex:
      entryPoints: ["websecure"]
      rule: "Host(`plex.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "plex"

  services:
    homeassistant:
      loadBalancer:
        servers: [{ url: "http://192.168.0.25:8123" }]
        passHostHeader: true
    pihole:
      loadBalancer:
        servers: [{ url: "https://192.168.0.36:4430" }]
        passHostHeader: true
    homebridge:
      loadBalancer:
        servers: [{ url: "http://192.168.50.97:8583" }]
        passHostHeader: true
    homebridge-pi:
      loadBalancer:
        servers: [{ url: "http://192.168.0.36:8581" }]
        passHostHeader: true
    plex:
      loadBalancer:
        servers: [{ url: "https://192.168.50.55:32400" }]
        passHostHeader: true