http:
  routers:
    pbs:
      entryPoints: ["websecure"]
      rule: "Host(`pbs.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "pbs"
    truenas:
      entryPoints: ["websecure"]
      rule: "Host(`truenas.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "truenas"
    unifi:
      entryPoints: ["websecure"]
      rule: "Host(`unifi.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "unifi"
    ceph:
      entryPoints: ["websecure"]
      rule: "Host(`ceph.test.teamfnb.com`)"
      middlewares: ["default-headers"]
      tls: { certResolver: "cloudflare" }
      service: "ceph"

  services:
    pbs:
      loadBalancer:
        servers: [{ url: "https://192.168.0.198:8007" }]
        passHostHeader: true
    truenas:
      loadBalancer:
        servers: [{ url: "https://192.168.0.241:443" }]
        passHostHeader: true
    unifi:
      loadBalancer:
        servers: [{ url: "https://192.168.0.1:443" }]
        passHostHeader: true
    ceph:
      loadBalancer:
        servers: [{ url: "https://192.168.50.57:8443/" }]
        passHostHeader: true