version: '3.9'

services:
  homebridge:
    image: homebridge/homebridge:latest
    networks:
      - host
    environment:
      - TZ=Europe/Paris
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - /mnt/cephfs/docker-cluster/Docker-Swarm/homebridge:/homebridge
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: stop-first # Crucial pour libérer le port physique avant de relancer
      placement:
        constraints:
          - node.role == manager
networks:
  host:
    external: true
    name: host