services:
  homebridge:
    image: homebridge/homebridge:latest
    # Suppression de container_name et restart (gérés par deploy)
    networks:
      - host
    environment:
      - TZ=Europe/Paris
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - /mnt/cephfs/docker-cluster/Docker-Swarm/homebridge:/homebridge
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  host:
    external: true
    name: host